# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.BigIntegerField(default=0)),
                ('sequence_id', models.BigIntegerField(default=0)),
                ('symbol', models.CharField(max_length=4)),
                ('trans_time', models.CharField(max_length=20)),
                ('_type', models.CharField(max_length=5)),
                ('amount', models.PositiveSmallIntegerField(default=0)),
                ('ex_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('money', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('FB', models.BigIntegerField(default=0)),
                ('SW', models.BigIntegerField(default=0)),
                ('HBC', models.BigIntegerField(default=0)),
                ('WMT', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='share',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mk_blockchain.User'),
        ),
    ]
